# Generated by Django 3.0.3 on 2020-02-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='num_views',
            field=models.IntegerField(default=0),
        ),
    ]
