# Generated by Django 3.0.3 on 2020-02-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_num_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='num_views',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
